config/routes.rb
WineCom::Application.routes.draw do
  root to: "users#index"

  devise_for :users

  resources :addresses, except: :show
  resources :wines
end

app/models/address.rb
class Address < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/appellation.rb
class Appellation < ActiveRecord::Base
  has_many :wineries
  belongs_to :region

  validates :name,      presence: true
  validates :region_id, presence: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many   :wines

  validates :quantity, presence: true
end

app/models/grape.rb
class Grape < ActiveRecord::Base
  has_many :wines

  validates :varietal, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many   :purchases
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :appellations
  has_many :wineries

  validates :name, presence: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  has_many :subscriptions_users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :addresses
  has_and_belongs_to_many :subscriptions
  has_many :orders
  has_many :purchases
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :winery
  belongs_to :grape

  has_many :carts

  validates :vintage,       presence: true
  validates :winery_id,     presence: true
  validates :grape_id,      presence: true
  validates :category_type, presence: true

  def serving_temperature_as_degree
    "43˚"
  end

  def alcohol_content_as_percent
     "15.5%" 
  end

end

app/models/winery.rb
class Winery < ActiveRecord::Base
  has_many :wines
  
  belongs_to :appellation
  belongs_to :region

  validates :name,           presence: true
  validates :appellation_id, presence: true
  validates :region_id,      presence: true

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    user = User.find_by(id: current_user.id)
    @addresses = user.addresses
  end

  def new
    @address = Address.new
  end

  def create
    address = Address.new(address_params)
    if address.save
      user = User.find_by(id: current_user.id)
      user.addresses << address
      redirect_to addresses_path
    else
      render :new
    end
  end

  def edit
    @address = Address.find_by(id: params[:id])
  end

  def update
    address = Address.find_by(id: params[:id])
    address.update_attributes(address_params)
    if address.save
      redirect_to addresses_path
    else
      render :edit
    end
  end

  def destroy
    address = Address.find_by(id: params[:id])
    address.destroy
    redirect_to addresses_path # Add notice for successful deletion
  end

  private

  def address_params
    params.require(:address).permit(:address1,
                                    :address2,
                                    :company,
                                    :city,
                                    :state,
                                    :zip)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController

  def index
    @wines = Wine.last(5)
  end

  def new
    @wine = Wine.new
    @winery_list = Winery.all(order: 'name')
    @grape_list = Grape.all
    @category_list = ['Red', 'White', 'Rose', 'Sparkling', 'Fortified']
  end

  def create
    wine = Wine.new(wine_params)
    if wine.save
      redirect_to wines_path
    else
      render :new
    end
  end

  def show
    @wine = Wine.find_by(id: params[:id])
  end

  def edit
    @wine = Wine.find_by(id: params[:id])
    @winery_list = Winery.all(order: 'name')
    @grape_list = Grape.all
    @category_list = ['Red', 'White', 'Rose', 'Sparkling', 'Fortified']
  end

  def update
    wine = Wine.find_by(id: params[:id])
    wine.update_attributes(wine_params)
    if wine.save
      redirect_to wines_path
    else
      render :edit
    end
  end

  def destroy
    wine = Wine.find_by(id: params[:id])
    wine.destroy
    redirect_to wines_path # Add notice for successful deletion
  end

  private

  def wine_params
    params.require(:wine).permit( :vintage, 
                                  :winery_id,
                                  :grape_id,
                                  :alcohol_percentage,
                                  :serving_temperature,
                                  :sweetness,
                                  :acidity,
                                  :tanin,
                                  :fruit,
                                  :body,
                                  :category_type
                                )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/edit.html.haml
.row
  %h3 Change your Address

=simple_form_for @address, :html => { method: :put } do |f|
  =f.error_notification

  .form-inputs
    .row
      .columns.large-3.small-7
        =f.input :address1, required: true, autofocus: true
    .row
      .columns.large-3.small-7
        =f.input :address2
    .row
      .columns.large-3.small-7
        =f.input :company
    .row
      .columns.large-3.small-7
        =f.input :city,     required: true
    .row
      .columns.large-3.small-7
        =f.input :state,    required: true
    .row
      .columns.large-3.small-7
        =f.input :zip,      required: true

  .form-actions
    .row
      =f.button :submit, "Change my address"

app/views/addresses/index.html.haml
-if @addresses.length > 0

  Your addresses:

  %ol
    -@addresses.each do |address|
      %li
        Address 1:
        = address.address1
        %br
        Address 2:
        = address.address2
        %br
        Company:
        = address.company
        %br
        City:
        = address.city
        %br
        State:
        = address.state
        %br
        Zip:
        = address.zip

        %br
        =link_to 'Edit Address', edit_address_path(address.id)
        =link_to 'Delete Address', address_path(address.id), method: :delete
        %br
-else
  You don't have any addresses listed! 
  %br
  Click the link to add one!

%br
=link_to 'Add New Address', new_address_path

app/views/addresses/new.html.haml
%h2 New Address

=simple_form_for @address do |f|
  =f.error_notification

  .form-inputs
    .row
      .columns.large-3.small-7
        =f.input :address1, required: true, autofocus: true
    .row
      .columns.large-3.small-7
        =f.input :address2
    .row
      .columns.large-3.small-7
        =f.input :company
    .row
      .columns.large-3.small-7
        =f.input :city,     required: true
    .row
      .columns.large-3.small-7
        =f.input :state,    required: true
    .row
      .columns.large-3.small-7
        =f.input :zip,      required: true

  .form-actions
    .row
      =f.button :submit, "Add Address"

app/views/layouts/_nav.html.haml
.fixed
  %nav.top-bar{"data-topbar"=>""}
    %ul.title-area
      %li.name
        %h1
          %a{href:root_path}
            Wine-Com
      %li.toggle-topbar.menu-icon
        %a{href:"#"}Menu

    %section.top-bar-section
      %ul.right
        %li.has-dropdown
          %a{href:"#"}Customer
          %ul.dropdown
            %li
              %a{href:"#"}First link in dropdown
        %li.has-dropdown
          %a{href:"#"}Admin
          %ul.dropdown
            %li
              =link_to 'New Wine', new_wine_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
 <meta charset="utf-8" />

 <!-- Uncomment to make IE8 render like IE7 -->
 <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

 <!-- Set the viewport width to device width for mobile -->
 <meta name="viewport" content="width=device-width, initial-scale=1.0" />

 <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

 <%= stylesheet_link_tag    "application" %>
 <%= javascript_include_tag "vendor/custom.modernizr" %>
 <%= csrf_meta_tags %>
</head>

<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render partial: 'layouts/nav'%>

  <%= yield %>

  
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/users/index.html.haml
-if current_user

  %h3 Account Dashboard

  %li=link_to 'Edit Profile', edit_user_registration_path
  %li=link_to 'Edit Password', edit_user_password_path
  %li=link_to 'Log Out', destroy_user_session_path, method: :delete
  %br
  =link_to 'Addresses', addresses_path

-else
  =link_to 'Login', new_user_session_path
  =link_to 'Sign up', new_user_registration_path

app/views/users/shared/_links.haml
-if controller_name != 'sessions'
  =link_to "Sign in", new_session_path(resource_name)
  %br

-if devise_mapping.registerable? && controller_name != 'registrations'
  =link_to "Sign up", new_registration_path(resource_name)
  %br

-if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  =link_to "Forgot your password?", new_password_path(resource_name)
  %br

-if devise_mapping.confirmable? && controller_name != 'confirmations'
  =link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br

-if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  =link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br

-if devise_mapping.omniauthable?
  -resource_class.omniauth_providers.each do |provider|
    =link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br
  

app/views/wines/edit.html.haml
.row
  %h3 Change wine info

=simple_form_for @wine, :html => { :method => :put } do |f|
  =f.error_notification

  .form-inputs
    .row
      .columns.large-3.small-7
        =f.input       :vintage, required: true
    .row
      .columns.large-3.small-7
        =f.association :winery, required: true, collection: @winery_list, label_method: :name
    .row
      .columns.large-3.small-7
        =f.association :grape, required: true, collection: @grape_list, label_method: :varietal
    .row
      .columns.large-3.small-7
        =f.input       :alcohol_percentage
    .row
      .columns.large-3.small-7
        =f.input       :serving_temperature
    .row
      .columns.large-3.small-7
        =f.input       :sweetness
    .row
      .columns.large-3.small-7
        =f.input       :acidity
    .row
      .columns.large-3.small-7
        =f.input       :tanin
    .row
      .columns.large-3.small-7
        =f.input       :fruit
    .row
      .columns.large-3.small-7
        =f.input       :body
    .row
      .columns.large-3.small-7
        =f.input       :category_type, required: true, collection: @category_list

  .form-actions
    .row
      .columns.large-3.small-7
        =f.button :submit, "Alter wine"

app/views/wines/index.html.haml
.row
  .columns.large-12.small-12
    %ol
      -@wines.each do |wine|
        %li= link_to "#{wine.vintage} #{wine.grape.varietal} from #{wine.winery.name} ", wine_path(wine.id)

app/views/wines/new.html.haml
%h2 New Wine

=simple_form_for @wine do |f|
  =f.error_notification

  .form-inputs
    .row
      .columns.large-3.small-7
        =f.input :vintage,            required: true
    .row
      .columns.large-3.small-7
        =f.association :winery,       required: true, collection: @winery_list, label_method: :name
    .row
      .columns.large-3.small-7
        =f.association :grape,        required: true, collection: @grape_list, label_method: :varietal
    .row
      .columns.large-3.small-7
        =f.input :alcohol_percentage
    .row
      .columns.large-3.small-7
        =f.input :serving_temperature
    .row
      .columns.large-3.small-7
        =f.input :sweetness
    .row
      .columns.large-3.small-7
        =f.input :acidity
    .row
      .columns.large-3.small-7
        =f.input :tanin
    .row
      .columns.large-3.small-7
        =f.input :fruit
    .row
      .columns.large-3.small-7
        =f.input :body
    .row
      .columns.large-3.small-7
        =f.input :category_type,      required: true, collection: @category_list


  .form-actions
    .row
      =f.button :submit, "Add Wine"

app/views/wines/show.html.haml
.row
  .columns.large-12.small-12
    %p= "This is a #{@wine.vintage} #{@wine.grape.varietal} from #{@wine.winery.name} in #{@wine.winery.appellation.name}, #{@wine.winery.region.name}"

.row
  .columns.large-12.small-12
    =link_to "Edit Wine", edit_wine_path(@wine.id)